# vim: set tabstop=4 shiftwidth=4 expandtab:

SAMPLE_VALID_IDENTITY_DOC='''{
  "devpayProductCodes" : null,
  "marketplaceProductCodes" : null,
  "privateIp" : "10.33.10.184",
  "region" : "ap-southeast-2",
  "version" : "2017-09-30",
  "instanceId" : "i-07fcad273fe2d4add",
  "billingProducts" : null,
  "instanceType" : "t2.micro",
  "availabilityZone" : "ap-southeast-2b",
  "kernelId" : null,
  "ramdiskId" : null,
  "accountId" : "351016140122",
  "architecture" : "x86_64",
  "imageId" : "ami-0a9591ce94104d964",
  "pendingTime" : "2018-09-26T06:10:52Z"
}'''

SAMPLE_VALID_IDENTITY_SIGNATURE="""MIAGCSqGSIb3DQEHAqCAMIACAQExCzAJBgUrDgMCGgUAMIAGCSqGSIb3DQEHAaCAJIAEggHmewog
ICJkZXZwYXlQcm9kdWN0Q29kZXMiIDogbnVsbCwKICAibWFya2V0cGxhY2VQcm9kdWN0Q29kZXMi
IDogbnVsbCwKICAicHJpdmF0ZUlwIiA6ICIxMC4zMy4xMC4xODQiLAogICJyZWdpb24iIDogImFw
LXNvdXRoZWFzdC0yIiwKICAidmVyc2lvbiIgOiAiMjAxNy0wOS0zMCIsCiAgImluc3RhbmNlSWQi
IDogImktMDdmY2FkMjczZmUyZDRhZGQiLAogICJiaWxsaW5nUHJvZHVjdHMiIDogbnVsbCwKICAi
aW5zdGFuY2VUeXBlIiA6ICJ0Mi5taWNybyIsCiAgImF2YWlsYWJpbGl0eVpvbmUiIDogImFwLXNv
dXRoZWFzdC0yYiIsCiAgImtlcm5lbElkIiA6IG51bGwsCiAgInJhbWRpc2tJZCIgOiBudWxsLAog
ICJhY2NvdW50SWQiIDogIjM1MTAxNjE0MDEyMiIsCiAgImFyY2hpdGVjdHVyZSIgOiAieDg2XzY0
IiwKICAiaW1hZ2VJZCIgOiAiYW1pLTBhOTU5MWNlOTQxMDRkOTY0IiwKICAicGVuZGluZ1RpbWUi
IDogIjIwMTgtMDktMjZUMDY6MTA6NTJaIgp9AAAAAAAAMYIBFzCCARMCAQEwaTBcMQswCQYDVQQG
EwJVUzEZMBcGA1UECBMQV2FzaGluZ3RvbiBTdGF0ZTEQMA4GA1UEBxMHU2VhdHRsZTEgMB4GA1UE
ChMXQW1hem9uIFdlYiBTZXJ2aWNlcyBMTEMCCQCWukjZ5V4aZzAJBgUrDgMCGgUAoF0wGAYJKoZI
hvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMTgwOTI2MDYxMDU2WjAjBgkqhkiG
9w0BCQQxFgQUbNKffZRJ/JQC1Z22KKbuL35qRvIwCQYHKoZIzjgEAwQuMCwCFGmZpo8yuAaueZwp
yaPseT/ncMxYAhRdD7tEC1WVui7KAzHyVzWQtGiLSQAAAAAAAA==
"""

SAMPLE_VALID_AWS_CERT="""-----BEGIN CERTIFICATE-----
MIIC7TCCAq0CCQCWukjZ5V4aZzAJBgcqhkjOOAQDMFwxCzAJBgNVBAYTAlVTMRkw
FwYDVQQIExBXYXNoaW5ndG9uIFN0YXRlMRAwDgYDVQQHEwdTZWF0dGxlMSAwHgYD
VQQKExdBbWF6b24gV2ViIFNlcnZpY2VzIExMQzAeFw0xMjAxMDUxMjU2MTJaFw0z
ODAxMDUxMjU2MTJaMFwxCzAJBgNVBAYTAlVTMRkwFwYDVQQIExBXYXNoaW5ndG9u
IFN0YXRlMRAwDgYDVQQHEwdTZWF0dGxlMSAwHgYDVQQKExdBbWF6b24gV2ViIFNl
cnZpY2VzIExMQzCCAbcwggEsBgcqhkjOOAQBMIIBHwKBgQCjkvcS2bb1VQ4yt/5e
ih5OO6kK/n1Lzllr7D8ZwtQP8fOEpp5E2ng+D6Ud1Z1gYipr58Kj3nssSNpI6bX3
VyIQzK7wLclnd/YozqNNmgIyZecN7EglK9ITHJLP+x8FtUpt3QbyYXJdmVMegN6P
hviYt5JH/nYl4hh3Pa1HJdskgQIVALVJ3ER11+Ko4tP6nwvHwh6+ERYRAoGBAI1j
k+tkqMVHuAFcvAGKocTgsjJem6/5qomzJuKDmbJNu9Qxw3rAotXau8Qe+MBcJl/U
hhy1KHVpCGl9fueQ2s6IL0CaO/buycU1CiYQk40KNHCcHfNiZbdlx1E9rpUp7bnF
lRa2v1ntMX3caRVDdbtPEWmdxSCYsYFDk4mZrOLBA4GEAAKBgEbmeve5f8LIE/Gf
MNmP9CM5eovQOGx5ho8WqD+aTebs+k2tn92BBPqeZqpWRa5P/+jrdKml1qx4llHW
MXrs3IgIb6+hUIB+S8dz8/mmO0bpr76RoZVCXYab2CZedFut7qc3WUH9+EUAH5mw
vSeDCOUMYQR7R9LINYwouHIziqQYMAkGByqGSM44BAMDLwAwLAIUWXBlk40xTwSw
7HX32MxXYruse9ACFBNGmdX2ZBrVNGrN9N2f6ROk0k9K
-----END CERTIFICATE-----
"""


SAMPLE_BOGUS_IDENTITY_DOC='''{
  "devpayProductCodes" : null,
  "marketplaceProductCodes" : "Free for life",
  "privateIp" : "10.33.10.14",
  "region" : "ap-southeast-2",
  "version" : "2017-09-30",
  "instanceId" : "i-07fcad2add",
  "billingProducts" : null,
  "instanceType" : "t2.micro",
  "availabilityZone" : "ap-southeast-2b",
  "kernelId" : null,
  "ramdiskId" : null,
  "accountId" : "351016140122",
  "architecture" : "x86_64",
  "imageId" : "ami-0a9591ce94104d964",
  "pendingTime" : "2018-09-26T06:10:52Z"
}'''

SAMPLE_BOGUS_IDENTITY_SIGNATURE="""
"""

SAMPLE_BOGUS_AWS_CERT="""-----BEGIN CERTIFICATE-----
MIICuzCCAiQCCQDrSGnlRgvSazANBgkqhkiG9w0BAQUFADCBoTELMAkGA1UEBhMC
VVMxCzAJBgNVBAgTAldBMRAwDgYDVQQHEwdTZWF0dGxlMRMwEQYDVQQKEwpBbWF6
b24uY29tMRYwFAYDVQQLEw1FQzIgQXV0aG9yaXR5MRowGAYDVQQDExFFQzIgQU1J
IEF1dGhvcml0eTEqMCgGCSqGSIb3DQEJARYbZWMyLWluc3RhbmNlLWlpZEBhbWF6
b24uY29tMB4XDTExMDgxMjE3MTgwNVoXDTIxMDgwOTE3MTgwNVowgaExCzAJBgNV
BAYTAlVTMQswCQYDVQQIEwJXQTEQMA4GA1UEBxMHU2VhdHRsZTETMBEGA1UEChMK
QW1hem9uLmNvbTEWMBQGA1UECxMNRUMyIEF1dGhvcml0eTEaMBgGA1UEAxMRRUMy
IEFNSSBBdXRob3JpdHkxKjAoBgkqhkiG9w0BCQEWG2VjMi1pbnN0YW5jZS1paWRA
YW1hem9uLmNvbTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAqaIcGFFTx/SO
1W5G91jHvyQdGP25n1Y91aXCuOOWAUTvSvNGpXrI4AXNrQF+CmIOC4beBASnHCx0
82jYudWBBl9Wiza0psYc9flrczSzVLMmN8w/c78F/95NfiQdnUQPpvgqcMeJo82c
gHkLR7XoFWgMrZJqrcUK0gnsQcb6kakCAwEAATANBgkqhkiG9w0BAQUFAAOBgQDF
VH0+UGZr1LCQ78PbBH0GreiDqMFfa+W8xASDYUZrMvY3kcIelkoIazvi4VtPO7Qc
yAiLr6nkk69Tr/MITnmmsZJZPetshqBndRyL+DaTRnF0/xvBQXj5tEh+AmRjvGtp
6iS1rQoNanN8oEcT2j4b48rmCmnDhRoBcFHwCYs/3w==
-----END CERTIFICATE-----
"""

SAMPLE_INVALID_IDENTITY_SIGNATURE="""
yaPseT/ncMxYAhRdD7tEC1WVui7KAzHyVzWQtGiLSQAAAAAAAA
"""

SAMPLE_INVALID_AWS_CERT="""
6iS1rQoNanN8oEcT2j4b48rmCmnDhRoBcFHwCYs/3w
"""

